apiVersion: v1
kind: Service
metadata:
  name: {{ include "inspectflow-cloud.fullname" . }}-backend
  labels:
    {{- include "inspectflow-cloud.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "inspectflow-cloud.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: http
