apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inspectflow-cloud.fullname" . }}-frontend
  labels:
    {{- include "inspectflow-cloud.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "inspectflow-cloud.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "inspectflow-cloud.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.port }}
            - name: https
              containerPort: 443
          envFrom:
            - configMapRef:
                name: {{ include "inspectflow-cloud.fullname" . }}-config
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
          {{- with .Values.frontend.resources }}
          resources:
{{ toYaml . | nindent 12 }}
          {{- end }}
