{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "inspectflow-cloud.fullname" . }}
  labels:
    {{- include "inspectflow-cloud.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.className }}
    kubernetes.io/ingress.class: {{ .Values.ingress.className | quote }}
    {{- end }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  tls:
    - hosts:
        - {{ .Values.global.publicHost | quote }}
      secretName: {{ .Values.global.tls.secretName | quote }}
  rules:
    - host: {{ .Values.global.publicHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "inspectflow-cloud.fullname" . }}-frontend
                port:
                  number: {{ .Values.frontend.service.port }}
{{- end }}
