apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inspectflow-cloud.fullname" . }}-secret
  labels:
    {{- include "inspectflow-cloud.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.backend.secrets.databaseUrl | quote }}
  AUTH_TOKEN_PEPPER: {{ .Values.backend.secrets.authTokenPepper | quote }}
